# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0144b371fe648b978f5fab0ceb96fa51f3ab1ba00a0ccdea0281aafb192faafd8e06359d6f4c0aafd6e3fd8791e4c7ea23fa2c93d2bc3ae7f8e44621793dbea0

test:
  secret_key_base: dcf0bc69e5d7b541f583bb2cfdf17a3ab2a74c215796df5d65e5683727d5625f9435f65bb958db17ca9fbfcbc6425c5d6e637f6c7193ce47e57704e37b3fe3f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
